// TypeScript 共通設定
module.exports = {
  compilerOptions: {
    target: "ES2022",
    module: "ESNext",
    lib: ["ES2022"],
    moduleResolution: "bundler",
    resolveJsonModule: true,
    allowJs: true,
    checkJs: false,
    outDir: "./dist",
    rootDir: "./src",
    removeComments: true,
    strict: true,
    noImplicitAny: true,
    strictNullChecks: true,
    strictFunctionTypes: true,
    strictBindCallApply: true,
    strictPropertyInitialization: true,
    noImplicitThis: true,
    alwaysStrict: true,
    noUnusedLocals: true,
    noUnusedParameters: true,
    noImplicitReturns: true,
    noFallthroughCasesInSwitch: true,
    noUncheckedIndexedAccess: true,
    noImplicitOverride: true,
    noPropertyAccessFromIndexSignature: true,
    allowUnusedLabels: false,
    allowUnreachableCode: false,
    exactOptionalPropertyTypes: true,
    skipLibCheck: true,
    forceConsistentCasingInFileNames: true,
    declaration: true,
    declarationMap: true,
    sourceMap: true,
    composite: true,
  },
};
